# Project Cancer Detection
# Breast  Cancer Wisconsin (Diagnostic) Data Set

In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"

col = ['id',
       'Clump Thickness',
       'Uniformity of Cell Size',
       'Uniformity of Cell Shape',
       'Marginal Adhesion',
       'Single Epithelial Cell Size',
       'Bare Nuclei',
       'Bland Chromatin',
       'Normal Nucleoli',
       'Mitoses',
       'Class']

df = pd.read_csv(url, names=col)

df.head()

,id,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

## Data Pre-Processing

In [3]:
np.where(df.isnull())

(array([], dtype=int64), array([], dtype=int64))

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           699 non-null    int64
 1   Clump Thickness              699 non-null    int64
 2   Uniformity of Cell Size      699 non-null    int64
 3   Uniformity of Cell Shape     699 non-null    int64
 4   Marginal Adhesion            699 non-null    int64
 5   Single Epithelial Cell Size  699 non-null    int64
 6   Bare Nuclei                  699 non-null    object
 7   Bland Chromatin              699 non-null    int64
 8   Normal Nucleoli              699 non-null    int64
 9   Mitoses                      699 non-null    int64
 10  Class                        699 non-null    int64
dtypes: int64(10), object(1)
memory usage: 60.2+ KB

In [5]:
df['Bare Nuclei'].describe()

count     699
unique     11
top         1
freq      402
Name: Bare Nuclei, dtype: object

In [6]:
df['Bare Nuclei'].value_counts()

Bare Nuclei
1     402
10    132
2      30
5      30
3      28
8      21
4      19
?      16
9       9
7       8
6       4
Name: count, dtype: int64

How to drop '?'

In [7]:
df[df['Bare Nuclei']=="?"]

,id,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
23,1057013,8,4,5,1,2,?,7,3,1,4
40,1096800,6,6,6,9,6,?,7,8,1,2
139,1183246,1,1,1,1,1,?,2,1,1,2
145,1184840,1,1,3,1,2,?,2,1,1,2
158,1193683,1,1,2,1,3,?,1,1,1,2
164,1197510,5,1,1,1,2,?,3,1,1,2
235,1241232,3,1,4,1,2,?,3,1,1,2
249,169356,3,1,1,1,2,?,3,1,1,2
275,432809,3,1,3,1,2,?,2,1,1,2
292,563649,8,8,8,1,2,?,6,10,1,4
294,606140,1,1,1,1,2,?,2,1,1,2
297,61634,5,4,3,1,2,?,2,3,1,2
315,704168,4,6,5,6,7,?,4,9,1,2
321,733639,3,1,1,1,2,?,3,1,1,2
411,1238464,1,1,1,1,1,?,2,1,1,2
617,1057067,1,1,1,1,1,?,1,1,1,2

In [8]:
df['Class'].value_counts()

Class
2    458
4    241
Name: count, dtype: int64

In [9]:
df['Bare Nuclei'].replace("?",np.nan,inplace=True)
df.dropna()

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9756\3763224388.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Bare Nuclei'].replace("?",np.nan,inplace=True)

,id,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2,1,1,1,2
695,841769,2,1,1,1,2,1,1,1,1,2
696,888820,5,10,10,3,7,3,8,10,2,4
697,897471,4,8,6,4,3,4,10,6,1,4
698,897471,4,8,8,5,4,5,10,4,1,4

Note that for class :2 is benign,4 is for malignant

In [10]:
df['Bare Nuclei'].value_counts()

Bare Nuclei
1     402
10    132
2      30
5      30
3      28
8      21
4      19
9       9
7       8
6       4
Name: count, dtype: int64

In [11]:
df['Class']=df['Class']/2-1

In [12]:
df['Class'].value_counts()

Class
0.0    458
1.0    241
Name: count, dtype: int64

In [13]:
df.columns

Index(['id', 'Clump Thickness', 'Uniformity of Cell Size',
       'Uniformity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           699 non-null    int64
 1   Clump Thickness              699 non-null    int64
 2   Uniformity of Cell Size      699 non-null    int64
 3   Uniformity of Cell Shape     699 non-null    int64
 4   Marginal Adhesion            699 non-null    int64
 5   Single Epithelial Cell Size  699 non-null    int64
 6   Bare Nuclei                  683 non-null    object
 7   Bland Chromatin              699 non-null    int64
 8   Normal Nucleoli              699 non-null    int64
 9   Mitoses                      699 non-null    int64
 10  Class                        699 non-null    float64
dtypes: float64(1), int64(9), object(1)
memory usage: 60.2+ KB

In [15]:
X=df.drop(['id','Class'],axis=1)
X_col=X.columns

In [16]:
y=df['Class']

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
X=StandardScaler().fit_transform(X.values)

### Training

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
df1=pd.DataFrame(X,columns=X_col)

In [21]:
df1.head()

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses
0,0.206936,-0.699995,-0.743299,-0.633247,-0.549561,-0.698853,-0.179662,-0.611825,-0.343912
1,0.206936,0.283845,0.266875,0.768621,1.710106,1.772867,-0.179662,-0.284112,-0.343912
2,-0.503866,-0.699995,-0.743299,-0.633247,-0.549561,-0.424217,-0.179662,-0.611825,-0.343912
3,0.562336,1.595632,1.613773,-0.633247,-0.097628,0.125054,-0.179662,1.354454,-0.343912
4,-0.148465,-0.699995,-0.743299,0.067687,-0.549561,-0.698853,-0.179662,-0.611825,-0.343912

In [23]:
X_train,X_test,y_train,y_test=train_test_split(df1,y,
                                              train_size=0.8,
                                              random_state=42)

In [24]:
from sklearn.preprocessing import MinMaxScaler
pd.DataFrame(MinMaxScaler().fit_transform(df.drop(['id','Class'],axis=1).values),columns=X_col).head()

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses
0,0.444444,0.000000,0.000000,0.000000,0.111111,0.000000,0.222222,0.000000,0.0
1,0.444444,0.333333,0.333333,0.444444,0.666667,1.000000,0.222222,0.111111,0.0
2,0.222222,0.000000,0.000000,0.000000,0.111111,0.111111,0.222222,0.000000,0.0
3,0.555556,0.777778,0.777778,0.000000,0.222222,0.333333,0.222222,0.666667,0.0
4,0.333333,0.000000,0.000000,0.222222,0.111111,0.000000,0.222222,0.000000,0.0

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
knn=KNeighborsClassifier(n_neighbors=5,p=2,
                         metric='minkowski')

In [30]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')  # or 'mean'
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

In [31]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [32]:
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score,cross_val_predict
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix, roc_auc_score

def print_score(clf, X_train, X_test, y_train, y_test, train=True):
    
    lb = preprocessing.LabelBinarizer()
    lb.fit(y_train)
    
    if train:
        res = clf.predict(X_train)
        print("Train result:\n")
        print("Accuracy score: {0:.4f}\n".format(accuracy_score(y_train, res)))
        print("Classification report:\n{}\n".format(classification_report(y_train, res)))
        print("Confusion matrix:\n{}\n".format(confusion_matrix(y_train, res)))
        print("ROC AUC: {0:.4f}\n".format(
            roc_auc_score(lb.transform(y_train), lb.transform(res))
        ))
        res=cross_val_score(clf,X_train,y_train,cv=10,scoring='accuracy')
        print("Average accuracy :\t{0:.4f}".format(np.mean(res)))
        print("Accuracy SD:\t\t{0:.4f}".format(np.std(res)))
        
    else:
        res_test = clf.predict(X_test)
        print("Test result:\n")
        print("Accuracy score: {0:.4f}\n".format(accuracy_score(y_test, res_test)))
        print("Classification report:\n{}\n".format(classification_report(y_test, res_test)))
        print("Confusion matrix:\n{}\n".format(confusion_matrix(y_test, res_test)))
        print("ROC AUC: {0:.4f}\n".format(
            roc_auc_score(lb.transform(y_test), lb.transform(res_test))
        ))

In [33]:
print_score(knn,X_train,X_test,y_train,y_test,train=True)
print("\n************************")
print_score(knn,X_train,X_test,y_train,y_test,train=False)

Train result:

Accuracy score: 0.9696

Classification report:
              precision    recall  f1-score   support

         0.0       0.98      0.97      0.98       363
         1.0       0.95      0.96      0.96       196

    accuracy                           0.97       559
   macro avg       0.97      0.97      0.97       559
weighted avg       0.97      0.97      0.97       559


Confusion matrix:
[[353  10]
 [  7 189]]

ROC AUC: 0.9684

Average accuracy :	0.9624
Accuracy SD:		0.0148

************************
Test result:

Accuracy score: 0.9714

Classification report:
              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98        95
         1.0       0.98      0.93      0.95        45

    accuracy                           0.97       140
   macro avg       0.97      0.96      0.97       140
weighted avg       0.97      0.97      0.97       140


Confusion matrix:
[[94  1]
 [ 3 42]]

ROC AUC: 0.9614

## Grid Search

In [34]:
from sklearn.model_selection import GridSearchCV

In [35]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [36]:
params={'n_neighbors':[1,2,3,4,5,6,7,8,10]}

In [37]:
grid_search_cv=GridSearchCV(KNeighborsClassifier(),
                            params,
                            n_jobs=-1,
                            verbose=1,
                            cv=10)

In [39]:
grid_search_cv.fit(X_train,y_train)

Fitting 10 folds for each of 9 candidates, totalling 90 fits

GridSearchCV(cv=10, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 10]},
             verbose=1)

In [40]:
grid_search_cv.best_estimator_

KNeighborsClassifier()

In [41]:
print_score(grid_search_cv,X_train,X_test,y_train,y_test,train=True)
print("\n************************")
print_score(grid_search_cv,X_train,X_test,y_train,y_test,train=False)

Train result:

Accuracy score: 0.9696

Classification report:
              precision    recall  f1-score   support

         0.0       0.98      0.97      0.98       363
         1.0       0.95      0.96      0.96       196

    accuracy                           0.97       559
   macro avg       0.97      0.97      0.97       559
weighted avg       0.97      0.97      0.97       559


Confusion matrix:
[[353  10]
 [  7 189]]

ROC AUC: 0.9684

Fitting 10 folds for each of 9 candidates, totalling 90 fits
Fitting 10 folds for each of 9 candidates, totalling 90 fits
Fitting 10 folds for each of 9 candidates, totalling 90 fits
Fitting 10 folds for each of 9 candidates, totalling 90 fits
Fitting 10 folds for each of 9 candidates, totalling 90 fits
Fitting 10 folds for each of 9 candidates, totalling 90 fits
Fitting 10 folds for each of 9 candidates, totalling 90 fits
Fitting 10 folds for each of 9 candidates, totalling 90 fits
Fitting 10 folds for each of 9 candidates, totalling 90 fits
Fitting 10 folds for each of 9 candidates, totalling 90 fits
Average accuracy :	0.9624
Accuracy SD:		0.0203

************************
Test result:

Accuracy score: 0.9714

Classification report:
              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98        95
         1.0       0.98      0.93      0.95        45

    accuracy                           0.97       140
   macro avg       0.97      0.96      0.97       140
weighted avg       0.97      0.97      0.97       140


Confusion matrix:
[[94  1]
 [ 3 42]]

ROC AUC: 0.9614

In [42]:
grid_search_cv.best_params_

{'n_neighbors': 5}

In [43]:
grid_search_cv.cv_results_['mean_test_score']

array([0.94993506, 0.94097403, 0.95529221, 0.95529221, 0.96243506,
       0.96243506, 0.9624026 , 0.9624026 , 0.96061688])

In [44]:
grid_search_cv.cv_results_

{'mean_fit_time': array([0.0056963 , 0.0049968 , 0.00589581, 0.00489635, 0.00489652,
        0.00639591, 0.0069953 , 0.00519657, 0.00509691]),
 'std_fit_time': array([0.00155133, 0.00134069, 0.00413113, 0.00113495, 0.00083069,
        0.00402725, 0.00511507, 0.00171939, 0.00137439]),
 'mean_score_time': array([0.01978686, 0.0145906 , 0.01838822, 0.0189882 , 0.01968777,
        0.0198874 , 0.0180887 , 0.01828814, 0.01588984]),
 'std_score_time': array([0.00820218, 0.00111315, 0.00599974, 0.00470889, 0.00727672,
        0.007511  , 0.0067848 , 0.00831348, 0.00383033]),
 'param_n_neighbors': masked_array(data=[1, 2, 3, 4, 5, 6, 7, 8, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value=999999),
 'params': [{'n_neighbors': 1},
  {'n_neighbors': 2},
  {'n_neighbors': 3},
  {'n_neighbors': 4},
  {'n_neighbors': 5},
  {'n_neighbors': 6},
  {'n_neighbors': 7},
  {'n_neighbors': 8},
  {'n_neighbors': 10}],
 'split0_test_score': array([0.98214286, 0.96428571, 0.98214286, 0.96428571, 0.96428571,
        0.96428571, 0.96428571, 0.94642857, 0.94642857]),
 'split1_test_score': array([0.96428571, 0.94642857, 0.94642857, 0.94642857, 0.94642857,
        0.94642857, 0.94642857, 0.94642857, 0.96428571]),
 'split2_test_score': array([0.92857143, 0.96428571, 0.94642857, 0.96428571, 0.98214286,
        0.98214286, 0.98214286, 0.98214286, 0.98214286]),
 'split3_test_score': array([0.94642857, 0.89285714, 0.92857143, 0.92857143, 0.94642857,
        0.94642857, 0.94642857, 0.94642857, 0.94642857]),
 'split4_test_score': array([0.96428571, 0.96428571, 0.96428571, 0.96428571, 0.96428571,
        0.96428571, 0.96428571, 0.96428571, 0.96428571]),
 'split5_test_score': array([0.96428571, 0.92857143, 0.94642857, 0.94642857, 0.98214286,
        0.98214286, 1.        , 1.        , 1.        ]),
 'split6_test_score': array([0.94642857, 0.94642857, 0.94642857, 0.96428571, 0.94642857,
        0.96428571, 0.96428571, 0.98214286, 0.96428571]),
 'split7_test_score': array([0.92857143, 0.94642857, 0.98214286, 0.98214286, 0.98214286,
        0.98214286, 0.98214286, 0.98214286, 0.96428571]),
 'split8_test_score': array([0.91071429, 0.91071429, 0.94642857, 0.92857143, 0.94642857,
        0.92857143, 0.92857143, 0.92857143, 0.92857143]),
 'split9_test_score': array([0.96363636, 0.94545455, 0.96363636, 0.96363636, 0.96363636,
        0.96363636, 0.94545455, 0.94545455, 0.94545455]),
 'mean_test_score': array([0.94993506, 0.94097403, 0.95529221, 0.95529221, 0.96243506,
        0.96243506, 0.9624026 , 0.9624026 , 0.96061688]),
 'std_test_score': array([0.02078115, 0.02263702, 0.01642937, 0.01642937, 0.01482672,
        0.01684064, 0.02036095, 0.02187107, 0.01930716]),
 'rank_test_score': array([8, 9, 6, 6, 1, 1, 3, 3, 5], dtype=int32)}

### SVM,Random Forest,XGBoost

In [45]:
from sklearn import svm

In [47]:
clf=svm.SVC(kernel='rbf',gamma='scale')
clf.fit(X_train,y_train)

SVC()

In [48]:
print_score(clf,X_train,X_test,y_train,y_test,train=True)
print("\n************************")
print_score(clf,X_train,X_test,y_train,y_test,train=False)

Train result:

Accuracy score: 0.9732

Classification report:
              precision    recall  f1-score   support

         0.0       0.99      0.97      0.98       363
         1.0       0.95      0.98      0.96       196

    accuracy                           0.97       559
   macro avg       0.97      0.97      0.97       559
weighted avg       0.97      0.97      0.97       559


Confusion matrix:
[[352  11]
 [  4 192]]

ROC AUC: 0.9746

Average accuracy :	0.9660
Accuracy SD:		0.0170

************************
Test result:

Accuracy score: 0.9786

Classification report:
              precision    recall  f1-score   support

         0.0       0.98      0.99      0.98        95
         1.0       0.98      0.96      0.97        45

    accuracy                           0.98       140
   macro avg       0.98      0.97      0.98       140
weighted avg       0.98      0.98      0.98       140


Confusion matrix:
[[94  1]
 [ 2 43]]

ROC AUC: 0.9725

In [49]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(random_state=42,n_estimators=100)
clf.fit(X_train,y_train)
print_score(clf,X_train,X_test,y_train,y_test,train=True)
print("\n************************")
print_score(clf,X_train,X_test,y_train,y_test,train=False)

Train result:

Accuracy score: 1.0000

Classification report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       363
         1.0       1.00      1.00      1.00       196

    accuracy                           1.00       559
   macro avg       1.00      1.00      1.00       559
weighted avg       1.00      1.00      1.00       559


Confusion matrix:
[[363   0]
 [  0 196]]

ROC AUC: 1.0000

Average accuracy :	0.9606
Accuracy SD:		0.0238

************************
Test result:

Accuracy score: 0.9643

Classification report:
              precision    recall  f1-score   support

         0.0       0.97      0.98      0.97        95
         1.0       0.95      0.93      0.94        45

    accuracy                           0.96       140
   macro avg       0.96      0.96      0.96       140
weighted avg       0.96      0.96      0.96       140


Confusion matrix:
[[93  2]
 [ 3 42]]

ROC AUC: 0.9561

In [50]:
import xgboost as xgb
xgb_clf=xgb.XGBClassifier(random_state=42,n_estimators=100)
xgb_clf.fit(X_train,y_train)
print_score(xgb_clf,X_train,X_test,y_train,y_test,train=True)
print("\n************************")
print_score(xgb_clf,X_train,X_test,y_train,y_test,train=False)

Train result:

Accuracy score: 1.0000

Classification report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       363
         1.0       1.00      1.00      1.00       196

    accuracy                           1.00       559
   macro avg       1.00      1.00      1.00       559
weighted avg       1.00      1.00      1.00       559


Confusion matrix:
[[363   0]
 [  0 196]]

ROC AUC: 1.0000

Average accuracy :	0.9517
Accuracy SD:		0.0240

************************
Test result:

Accuracy score: 0.9571

Classification report:
              precision    recall  f1-score   support

         0.0       0.96      0.98      0.97        95
         1.0       0.95      0.91      0.93        45

    accuracy                           0.96       140
   macro avg       0.96      0.95      0.95       140
weighted avg       0.96      0.96      0.96       140


Confusion matrix:
[[93  2]
 [ 4 41]]

ROC AUC: 0.9450